# ç½‘ç«™æ ‡é¢˜
logo_title: Alter
# åˆå§‹åŒ–é£æ ¼ black/light
style: black

# é¦–é¡µURL
link: Your_URL

#æ ‡è¯­:
words: Maybe it's time to change.

# ä½ çš„æ˜µç§°
author: Alongite
# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰
gender: /img/male.png #/img/female.png

favicon: /img/favicon.ico

# èœå•æ é…ç½®
menu:
  å…³äºæˆ‘ğŸ‘€: /about
  è®¿é—®ä¸»ç«™ğŸ‰: https://github.com/alongite
  GithubğŸ’: https://github.com/alongite

# åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
# è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable:false
  appId: NOsswOncKgc8HOxqo9oxIWlX-gzGzoHsz
  appKey: z1FihjWEbS8uIfUQdmCtK7zz


highlight:
  enable: true